//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinancialCRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bill
    {
        public int BillId { get; set; }
        public string BillTitle { get; set; }
        public Nullable<decimal> BillAmount { get; set; }
        public string BillPeriod { get; set; }
    }
}
